spring:
  application:
    name: alibaba-gateway
  profiles:
    active: dev


server:
  port: 5555
  undertow:
    uri-encoding: UTF-8
    accesslog:
      enabled: false
      pattern: combined
  servlet:
    session:
      timeout: PT120M

  
logging:
  path: /data/${spring.application.name}/logs

# we enable some of the management endpoints to make it possible to restart the application
management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true


client:
  http:
    request:
      connectTimeout: 8000
      readTimeout: 30000
      
